import { Inter } from "next/font/google";
import "./globals.css";
import Link from "next/link";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <nav className=" bg-white/45 p-4 border-b-2">
          <div className="flex justify-between  items-end">
            <Link href="/" className="text-black text-base font-bold">
              Google Cloud
            </Link>
            <Link href="/" className="text-black text-base font-bold">
              Home
            </Link>
          </div>
        </nav>
        {children}
      </body>
    </html>
  );
}
